package org.javaplus.netbeans.persistence.ql.view;

import javax.swing.tree.TreeModel;
import org.javaplus.netbeans.persistence.ql.query.QueryResult;
import org.javaplus.netbeans.persistence.ql.view.model.RowModelImpl;
import org.javaplus.netbeans.persistence.ql.view.model.TreeModelImpl;
import org.netbeans.swing.outline.DefaultOutlineModel;
import org.netbeans.swing.outline.OutlineModel;
import org.netbeans.swing.outline.RenderDataProvider;
import org.netbeans.swing.outline.RowModel;

/**
 *
 * @author Roger Suen
 */
public class DataView extends java.awt.Panel {

    private final QueryResult queryResult;
    /** Creates new form DataView */
    public DataView(QueryResult queryResult) {
        this.queryResult = queryResult;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        outlineScrollPane = new javax.swing.JScrollPane();
        outline = new org.netbeans.swing.outline.Outline();
        footerPanel = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(headerPanel);

        TreeModel treeModel = new TreeModelImpl(queryResult.getResult(),
            queryResult.getEntityManager());
        RowModel rowModel = new RowModelImpl();
        OutlineModel outlineModel =
        DefaultOutlineModel.createOutlineModel(treeModel, rowModel,
            true, "Object");
        RenderDataProvider render = new RenderDataProviderImpl();

        outline.setModel(outlineModel);
        outline.setRenderDataProvider(render);
        outlineScrollPane.setViewportView(outline);

        add(outlineScrollPane);
        add(footerPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private org.netbeans.swing.outline.Outline outline;
    private javax.swing.JScrollPane outlineScrollPane;
    // End of variables declaration//GEN-END:variables

}
